language: cpp
dist: bionic
compiler:
  - gcc
  - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default

script: 
  - qmake
  - make release
  - ./cpp_benchmark_add_one
